import React, { useMemo } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Link } from 'wouter';
import { CreditCard, TrendingDown, TrendingUp } from 'lucide-react';
import { useApp } from '@/store';

const totals = (records: typeof useApp extends never ? never : any[]) => ({ total: records.reduce((sum, record) => sum + record.amount, 0), paid: records.reduce((sum, record) => sum + (record.paidAmount ?? (record.status === 'paid' ? record.amount : 0)), 0) });
export default function FeeDashboard() {
  const { state } = useApp();
  const feeRecords = state.feeRecords.map(record => ({ ...record, department: record.studentType ?? state.students.find(student => student.id === record.studentId)?.department }));
  const school = totals(feeRecords.filter(record => record.department === 'school'));
  const madrasa = totals(feeRecords.filter(record => record.department === 'madrasa'));
  const paid = feeRecords.reduce((sum, record) => sum + (record.paidAmount ?? (record.status === 'paid' ? record.amount : 0)), 0);
  const pending = Math.max(0, feeRecords.reduce((sum, record) => sum + record.amount, 0) - paid);
  const chartData = useMemo(() => [{ name: 'School', total: school.total, collected: school.paid, pending: school.total - school.paid }, { name: 'Dars-e-Nizami', total: madrasa.total, collected: madrasa.paid, pending: madrasa.total - madrasa.paid }], [school.total, school.paid, madrasa.total, madrasa.paid]);
  const paidPending = [{ name: 'Paid', value: paid }, { name: 'Pending', value: pending }].filter(item => item.value > 0);
  return <div className="fee-dashboard-page"><div className="fee-dashboard-heading"><div><span className="fee-kicker">FEE MANAGEMENT SYSTEM</span><h1>Financial control, at a glance.</h1><p>Monitor School and Dars-e-Nizami collections from one focused workspace.</p></div><CreditCard className="fee-heading-icon" /></div><div className="fee-kpi-grid"><div><TrendingUp /><span>Total collected</span><strong>Rs. {paid.toLocaleString()}</strong></div><div><TrendingDown /><span>Outstanding balance</span><strong>Rs. {pending.toLocaleString()}</strong></div><div><CreditCard /><span>Fee records</span><strong>{feeRecords.length}</strong></div></div><div className="fee-chart-grid"><section className="fee-chart-panel"><div className="fee-panel-heading"><div><span>SCHOOL FEE</span><h2>School collection</h2></div><Link href="/fees-portal/school">Open system</Link></div><div className="fee-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={[chartData[0]]}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eadfce" /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="collected" name="Collected" fill="#a86426" radius={[5, 5, 0, 0]} /><Bar dataKey="pending" name="Pending" fill="#d9c1a2" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="fee-chart-panel"><div className="fee-panel-heading"><div><span>DARS-E-NIZAMI FEE</span><h2>Madrasa collection</h2></div><Link href="/fees-portal/madrasa">Open system</Link></div><div className="fee-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={[chartData[1]]}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eadfce" /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="collected" name="Collected" fill="#536b9c" radius={[5, 5, 0, 0]} /><Bar dataKey="pending" name="Pending" fill="#b8c2d5" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="fee-chart-panel fee-chart-wide"><div className="fee-panel-heading"><div><span>OVERALL STATUS</span><h2>Paid versus pending</h2></div><span className="fee-total-label">Rs. {(paid + pending).toLocaleString()} total</span></div><div className="fee-status-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={paidPending} dataKey="value" nameKey="name" innerRadius={55} outerRadius={88} paddingAngle={4}>{paidPending.map((entry, index) => <Cell key={entry.name} fill={index === 0 ? '#a86426' : '#d9c1a2'} />)}</Pie><Tooltip formatter={(value: number) => [`Rs. ${value.toLocaleString()}`, 'Amount']} /></PieChart></ResponsiveContainer><div><strong>Rs. {paid.toLocaleString()}</strong><span>Collected</span><strong>Rs. {pending.toLocaleString()}</strong><span>Pending</span></div></div></section></div></div>;
}
