import React, { useEffect, useState } from 'react';
import { Check, Edit, Hash, Plus, Save, Trash2, X } from 'lucide-react';
import { toast } from 'sonner';
import { useApp } from '@/store';

export default function MadrasaSettings() {
  const { state, dispatch } = useApp();
  const [selectedClass, setSelectedClass] = useState(state.madrasaClasses[0] ?? '');
  const [newClass, setNewClass] = useState('');
  const [newSubject, setNewSubject] = useState('');
  const [editingClass, setEditingClass] = useState<number | null>(null);
  const [classValue, setClassValue] = useState('');
  const [editingSubject, setEditingSubject] = useState<number | null>(null);
  const [subjectValue, setSubjectValue] = useState('');
  const [range, setRange] = useState({ start: 0, end: 0 });
  const subjects = state.madrasaSubjectsByClass[selectedClass] ?? [];

  useEffect(() => {
    const configured = state.rollNumberRanges.find(item => item.department === 'madrasa' && item.className === selectedClass);
    setRange(configured ? { start: configured.rangeStart, end: configured.rangeEnd } : { start: 0, end: 0 });
  }, [selectedClass, state.rollNumberRanges]);

  const addClass = () => { const value = newClass.trim(); if (!value || state.madrasaClasses.includes(value)) return; dispatch({ type: 'SET_MADRASA_CLASSES', payload: [...state.madrasaClasses, value] }); dispatch({ type: 'SET_MADRASA_CLASS_SUBJECTS', payload: { className: value, subjects: [] } }); setSelectedClass(value); setNewClass(''); toast.success('جماعت شامل ہو گئی'); };
  const saveClass = (index: number) => { const value = classValue.trim(); const old = state.madrasaClasses[index]; if (!value || state.madrasaClasses.some((item, itemIndex) => item === value && itemIndex !== index)) return; dispatch({ type: 'SET_MADRASA_CLASSES', payload: state.madrasaClasses.map((item, itemIndex) => itemIndex === index ? value : item) }); dispatch({ type: 'SET_MADRASA_CLASS_SUBJECTS', payload: { className: value, subjects: state.madrasaSubjectsByClass[old] ?? [] } }); if (selectedClass === old) setSelectedClass(value); setEditingClass(null); };
  const removeClass = (name: string) => { if (!confirm(`کیا ${name} حذف کریں؟`)) return; const remaining = state.madrasaClasses.filter(item => item !== name); dispatch({ type: 'SET_MADRASA_CLASSES', payload: remaining }); setSelectedClass(selectedClass === name ? (remaining[0] ?? '') : selectedClass); };
  const addSubject = () => { const value = newSubject.trim(); if (!selectedClass || !value || subjects.includes(value)) return; dispatch({ type: 'SET_MADRASA_CLASS_SUBJECTS', payload: { className: selectedClass, subjects: [...subjects, value] } }); setNewSubject(''); toast.success('مضمون شامل ہو گیا'); };
  const saveSubject = (index: number) => { const value = subjectValue.trim(); if (!value || subjects.some((item, itemIndex) => item === value && itemIndex !== index)) return; dispatch({ type: 'SET_MADRASA_CLASS_SUBJECTS', payload: { className: selectedClass, subjects: subjects.map((item, itemIndex) => itemIndex === index ? value : item) } }); setEditingSubject(null); };
  const saveRange = () => { if (!selectedClass || !Number.isInteger(range.start) || !Number.isInteger(range.end) || range.start < 1 || range.start >= range.end) { toast.error('درست رول نمبر رینج درج کریں'); return; } dispatch({ type: 'SET_MADRASA_CLASS_ROLL_RANGE', payload: { className: selectedClass, rangeStart: range.start, rangeEnd: range.end } }); toast.success('رول نمبر رینج محفوظ ہو گئی'); };

  return <div className="madrasa-module-page urdu-text" dir="rtl"><div className="madrasa-module-heading"><div><span className="madrasa-kicker">مدرسہ کی ترتیبات</span><h1>کلاس، مضامین اور رول نمبر</h1><p>ہر جماعت کی ترتیبات الگ محفوظ کریں۔</p></div></div><div className="madrasa-settings-grid">
    <section className="madrasa-settings-panel"><div className="madrasa-settings-title"><Hash /><div><h2>جماعت وار رول نمبر</h2><p>جماعت منتخب کریں، پھر اس کی رینج محفوظ کریں۔</p></div></div><label className="madrasa-picker">جماعت<select value={selectedClass} onChange={event => setSelectedClass(event.target.value)}>{state.madrasaClasses.map(name => <option key={name} value={name}>{name}</option>)}</select></label><div className="madrasa-range-fields"><label>ابتدائی رول نمبر<input type="number" value={range.start || ''} onChange={event => setRange({ ...range, start: Number(event.target.value) })} /></label><label>آخری رول نمبر<input type="number" value={range.end || ''} onChange={event => setRange({ ...range, end: Number(event.target.value) })} /></label></div><button className="madrasa-primary-button" onClick={saveRange}><Save className="w-4 h-4" /> رینج محفوظ کریں</button></section>
    <section className="madrasa-settings-panel"><div className="madrasa-settings-title"><Check /><div><h2>جماعتوں کا انتظام</h2><p>{state.madrasaClasses.length} جماعتیں</p></div></div><div className="madrasa-add-line"><input placeholder="نئی جماعت" value={newClass} onChange={event => setNewClass(event.target.value)} onKeyDown={event => event.key === 'Enter' && addClass()} /><button onClick={addClass} title="جماعت شامل کریں"><Plus className="w-4 h-4" /></button></div><div className="madrasa-settings-list">{state.madrasaClasses.map((name, index) => <div key={`${name}-${index}`}>{editingClass === index ? <input value={classValue} onChange={event => setClassValue(event.target.value)} /> : <button className={selectedClass === name ? 'selected' : ''} onClick={() => setSelectedClass(name)}>{name}</button>}<span>{editingClass === index ? <><button onClick={() => saveClass(index)}><Check className="w-4 h-4" /></button><button onClick={() => setEditingClass(null)}><X className="w-4 h-4" /></button></> : <><button onClick={() => { setEditingClass(index); setClassValue(name); }}><Edit className="w-4 h-4" /></button><button onClick={() => removeClass(name)}><Trash2 className="w-4 h-4" /></button></>}</span></div>)}</div></section>
    <section className="madrasa-settings-panel"><div className="madrasa-settings-title"><BookOpenIcon /><div><h2>جماعت وار مضامین</h2><p>منتخب جماعت کے مضامین ہی دکھائے جاتے ہیں۔</p></div></div><label className="madrasa-picker">جماعت<select value={selectedClass} onChange={event => setSelectedClass(event.target.value)}>{state.madrasaClasses.map(name => <option key={name} value={name}>{name}</option>)}</select></label><div className="madrasa-subject-context"><strong>{selectedClass}</strong><span>{subjects.length} مضامین</span></div><div className="madrasa-add-line"><input placeholder="نیا مضمون" value={newSubject} onChange={event => setNewSubject(event.target.value)} onKeyDown={event => event.key === 'Enter' && addSubject()} dir="rtl" /><button onClick={addSubject} title="مضمون شامل کریں"><Plus className="w-4 h-4" /></button></div><div className="madrasa-settings-list">{subjects.map((subject, index) => <div key={`${subject}-${index}`}>{editingSubject === index ? <input value={subjectValue} onChange={event => setSubjectValue(event.target.value)} dir="rtl" /> : <span>{subject}</span>}<span>{editingSubject === index ? <><button onClick={() => saveSubject(index)}><Check className="w-4 h-4" /></button><button onClick={() => setEditingSubject(null)}><X className="w-4 h-4" /></button></> : <><button onClick={() => { setEditingSubject(index); setSubjectValue(subject); }}><Edit className="w-4 h-4" /></button><button onClick={() => dispatch({ type: 'SET_MADRASA_CLASS_SUBJECTS', payload: { className: selectedClass, subjects: subjects.filter((_, itemIndex) => itemIndex !== index) } })}><Trash2 className="w-4 h-4" /></button></>}</span></div>)}</div></section>
  </div></div>;
}

function BookOpenIcon() { return <Hash />; }
